<%@ page import="java.util.*, java.text.DecimalFormat, model.Bill" %>
<%@ include file="header.jsp" %>
<%@ page contentType="text/html;charset=UTF-8" %>

<!DOCTYPE html>
<html>
<head>
    <title>All Sales</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container mt-5">
    <h3 class="bg-primary text-white text-center p-3 rounded">All Sales</h3>

    <table class="table table-bordered table-hover table-sm">
        <thead class="table-dark">
            <tr>
                <th>#</th>
                <th>Customer</th>
                <th>Books Purchased</th>
                <th>Total Amount (LKR)</th>
                <th>Bill Date</th>
                <th>Invoice Generated By</th>
            </tr>
        </thead>
        <tbody>
        <%
            List<Bill> salesList = (List<Bill>) request.getAttribute("salesList");
            DecimalFormat df = new DecimalFormat("#,##0.00");
            int count = 1;
            if (salesList != null) {
                for (Bill sale : salesList) {
        %>
            <tr>
                <td><%= count++ %></td>
                <td><%= sale.getCustomerName() %> (<%= sale.getAccountNumber() %>)</td>
                <td><%= sale.getBooksPurchased() %></td>
                <td class="text-end"><%= df.format(sale.getTotalAmount()) %></td>
                <td><%= sale.getBillingTime() %></td>
                <td><%= sale.getStaffUsername()%></td>
            </tr>
        <%
                }
            }
        %>
        </tbody>
    </table>
    
    		<% if (salesList != null) { %>
			
			    <div class="mt-3 text-start">
			        <strong>Total Invoices: <%= salesList.size() %></strong>
			    </div>
			    
			<% } %>
</div>
</body>
</html>
